services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app/src
    environment:
      - CORS_ORIGINS=["http://localhost:5173"]
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /app/src

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src
